name: attendance_tasks
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  provider:
  hive_local_storage:
  intl:
  shared_preferences:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  hive_generator:

flutter:

  uses-material-design: true

